# relative pos of the base_link w.r.t shelf_frame expressed in shelf_frame
# format: [x y z roll pitch yaw] in meters and radians

base_pos_dict: { column_1: [-0.7579, 0.0, 0.0, 0.0, 0.0, 0.0],
                 column_2: [-0.7579, -0.25, 0.0, 0.0, 0.0, 0.0],
                 column_3: [-0.7579, -0.5, 0.0, 0.0, 0.0, 0.0]}
