grasping_param_dict:
  pre_distance: -0.2
  lifting_height: 0.02
  sideGraspingTrialAngles: 10
  sideGraspingTolerance: 30
  base_retreat_distance: 0.6
  sideGraspingTrials: 1
  sideGraspingSegReach: 0.02

  sideGraspingRow1_pitch: -10.0
  sideGraspingRow1_reach: 0.1
  sideGraspingRow1_liftAngle: -1
  sideGraspingBookX: -0.02
  sideGraspingBookY: 0.02
  sideGraspingBookZ: 0.04

  gripperWidth: 0.085

  topGraspingTrials: 1
  topGraspingPitch: 12
  topGraspingPitchTolerance: 4
  topGraspingPitchTrials: 2
  
  topGraspingRoll: 180
  topGrasping_pre_distance: -0.2
  topGraspHeight: 0.06
  topGraspingFrame: 'base_link'
  topGraspingShakingNumber: 2
  topGraspingReachSeg: 0.02
  topGraspingTouchSteps: 10
  topGraspingTouchTolerance: 0.02
  topGraspingYshiftTolerance: 0.02
  topGraspingLiftingHeight: 0.04
  topGraspingMaxReachingHeight: 0.1

  topGraspingYawTolerance: 45
  topGraspingYawTrials: 6

  row_height:
    row_1: 0
    row_2: 1.27
    row_3: 1.04
    row_4: 0.78
