grasping_param_dict:
  pre_distance: -0.1
  ft_switch: True
  lifting_height: 0.04
  topGraspHeight: 0.1
  topGraspingFrame: 'base_link'
  sideGraspingTrialAngles: 10
  sideGraspingTolerance: 30
  base_retreat_distance: 0.5
  topGraspingTrials: 2
  sideGraspingTrials: 2
  gripperWidth: 0.085