grasping_param_dict:
  pre_distance: -0.2
  ft_switch: True
  lifting_height: 0.04
  sideGraspingTrialAngles: 10
  sideGraspingTolerance: 30
  base_retreat_distance: 0.6
  sideGraspingTrials: 2

  gripperWidth: 0.085

  topGraspingTrials: 1
  topGraspingPitch: 20
  topGraspingPitchTolerance: 10
  topGraspingPitchTrials: 4
  
  topGraspingRoll: 180
  topGrasping_pre_distance: -0.2
  topGraspHeight: 0.1
  topGraspingFrame: 'base_link'
  topGraspingShakingNumber: 2
  topGraspingReachSeg: 0.01

  topGraspingYawTolerance: 45
  topGraspingYawTrials: 6

  row_height:
    row_1: 0
    row_2: 1.27
    row_3: 1.04
    row_4: 0.78
