left_arm_joint_pos_dict: { start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_A_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_A_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
                           }
