right_arm_joint_pos_dict: { start: [-1.287058373, 0.537414654849, -0.514067217975, -2.064004335, 1.07455044206, -0.71659260978, -0.990427049319],

                           bin_A_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_A_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_B_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_B_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_C_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_C_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_D_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_D_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_E_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_E_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_F_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_F_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_G_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_G_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_H_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_H_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_I_start: [0.141293090103, 1.15032887973, -0.514059822446, -2.00656583352, 2.76858742441, -0.843351460522, -0.869325487592],
                           bin_I_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_J_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_J_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_K_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_K_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_L_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_L_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
                           }