right_arm_joint_pos_dict: { start: [-1.287058373, 0.537414654849, -0.514067217975, -2.064004335, 1.07455044206, -0.71659260978, -0.990427049319],

                           bin_A_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_A_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_B_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_B_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_C_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_C_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_D_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_D_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_E_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_E_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_F_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_F_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_G_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_G_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_H_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_H_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_I_start: [-0.513148800762, 0.376343822518, -0.465621104982, -1.89371888245, 9.71145746538, -1.34773418783, 6.63808819186],
                           bin_I_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_J_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_J_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_K_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_K_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],

                           bin_L_start: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                           bin_L_out: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
                           }