json_file:
  package: pr2_amazon_challenge_sim
  relative_path: config/test_case_1.json

# pose relative to bin [x y z r p y]
gazebo_models:
  cheezit_big_original:
    bin: bin_G
    pose: [0.16, 0.0, 0.077, 0.0, 1.5708, 0.5]
    
  crayola_64_ct:
    bin: bin_I
    pose: [0.14, 0.0, 0.06, 0.0, 0.0, -0.3]
