#!/usr/bin/python



#   logitech_camera_planning_scene
#
#   Created on: April 29, 2015
#   Authors:   Francisco Vina
#             fevb <at> kth.se
#

#  Copyright (c) 2015, Francisco Vina, CVAP, KTH
#    All rights reserved.

#    Redistribution and use in source and binary forms, with or without
#    modification, are permitted provided that the following conditions are met:
#       * Redistributions of source code must retain the above copyright
#         notice, this list of conditions and the following disclaimer.
#       * Redistributions in binary form must reproduce the above copyright
#         notice, this list of conditions and the following disclaimer in the
#         documentation and/or other materials provided with the distribution.
#       * Neither the name of KTH nor the
#         names of its contributors may be used to endorse or promote products
#         derived from this software without specific prior written permission.

#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
#    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#    DISCLAIMED. IN NO EVENT SHALL KTH BE LIABLE FOR ANY
#    DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


import rospy
from moveit_commander import PlanningSceneInterface
import shape_msgs.msg
import moveit_msgs.msg
from tf import TransformListener
import tf
from tf_conversions import posemath
from geometry_msgs.msg import Pose, PoseStamped
import rospkg
import sys
import numpy as np
import PyKDL as kdl
import copy
import random

if __name__=='__main__':
    rospy.init_node('logitech_camera_planning_scene')

    rospy.loginfo('[logitech_camera_planning_scene]: Waiting for Moveit to load')
    rospy.wait_for_service('/move_group/ompl/set_parameters')

    #rospy.sleep(20.0)



    planning_scene = PlanningSceneInterface()
    rospy.sleep(5.0)
    while not rospy.is_shutdown():
        try:
            camera_size = rospy.get_param('/camera_size', [0.2, 0.12, 0.075])
            break
        except:
            rospy.sleep(random.uniform(0,1))
            continue

    camera_pose = kdl.Frame(kdl.Rotation.Identity(), kdl.Vector(0.12+0.37*0.5, 0.0, -camera_size[2]*0.5))


    camera_pose_stamped = PoseStamped()
    camera_pose_stamped.pose = posemath.toMsg(camera_pose)
    camera_pose_stamped.header.frame_id = 'head_mount_link'
    camera_pose_stamped.header.stamp - rospy.Time.now()
    planning_scene.attach_box('head_mount_link', 'logitech_camera', camera_pose_stamped, camera_size)
