#!/usr/bin/env python

#   test_
#
#   Created on: April 8, 2015
#   Authors:   Francisco Vina
#             fevb <at> kth.se
#

#  Copyright (c) 2015, Francisco Vina, CVAP, KTH
#    All rights reserved.

#    Redistribution and use in source and binary forms, with or without
#    modification, are permitted provided that the following conditions are met:
#       * Redistributions of source code must retain the above copyright
#         notice, this list of conditions and the following disclaimer.
#       * Redistributions in binary form must reproduce the above copyright
#         notice, this list of conditions and the following disclaimer in the
#         documentation and/or other materials provided with the distribution.
#       * Neither the name of KTH nor the
#         names of its contributors may be used to endorse or promote products
#         derived from this software without specific prior written permission.

#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
#    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#    DISCLAIMED. IN NO EVENT SHALL KTH BE LIABLE FOR ANY
#    DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import pr2_moveit_utils.pr2_moveit_utils as pr2_moveit_utils
import PyKDL as kdl
import rospy
import moveit_commander
import numpy as np
from tf_conversions import posemath
from geometry_msgs.msg import Pose, PoseStamped


if __name__ == "__main__":

    rospy.init_node('test_pr2_moveit_tool_frame')
    right_arm = moveit_commander.MoveGroupCommander('right_arm')


    # specify the torso to tool transform
    T_torso_tool = kdl.Frame(kdl.Rotation.RPY(2.7429696524243528, 0.9886006739293244, -2.203256332732016), kdl.Vector( 0.755265,   -0.239342,   -0.207825))


    # set ft=True in case the arm has an FT sensor
    pr2_moveit_utils.go_tool_frame(right_arm, T_torso_tool, base_frame_id ='torso_lift_link', ft=False, wait=True)

