#kinect_chest
camera/kinect_chest/color_only_mode: false
camera/kinect_chest/rgb: /kinect_chest/hd/image_color_rect
camera/kinect_chest/rgb_info: /kinect_chest/hd/camera_info
camera/kinect_chest/depth: /kinect_chest/hd/image_depth_rect
camera/kinect_chest/robot_frame: kinect_chest_rgb_optical_frame

#kinect_head
camera/kinect_head/color_only_mode: false
camera/kinect_head/rgb: /kinect_head/hd/image_color_rect
camera/kinect_head/rgb_info: /kinect_head/hd/camera_info
camera/kinect_head/depth: /kinect_head/hd/image_depth_rect
camera/kinect_head/robot_frame: kinect_head_rgb_optical_frame

#kinect_external
camera/kinect_external/color_only_mode: false
camera/kinect_external/rgb: /kinect_external/hd/image_color_rect
camera/kinect_external/rgb_info: /kinect_external/hd/camera_info
camera/kinect_external/depth: /kinect_external/hd/image_depth_rect
camera/kinect_external/robot_frame: kinect_external_rgb_optical_frame

#ids_left
camera/ids_left/color_only_mode: true
camera/ids_left/rgb: /ids_left/image_raw
camera/ids_left/rgb_info: /ids_left/camera_info
camera/ids_left/robot_frame: ids_left_rgb_optical_center

#ids_right
camera/ids_right/color_only_mode: true
camera/ids_right/rgb: /ids_right/image_raw
camera/ids_right/rgb_info: /ids_right/camera_info
camera/ids_right/robot_frame: ids_right_rgb_optical_center
